apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dx317pzhh-python 
  janus-idp.io/tekton: dx317pzhh-python
  backstage.io/kubernetes-id: dx317pzhh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dx317pzhh-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml