apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dx317pzhh-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dx317pzhh-python 
  name: dx317pzhh-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dx317pzhh-python 
